coverage:
  precision: 1

  status:
    project:
      default:
        target: 70%    # the (on purpose low) required coverage value
        threshold: 2%  # the permitted delta in hitting the target
    patch:
      default:
        target: 0%     # the (on purpose low) required coverage value

comment: false

ignore:
  - "inst/include/armadillo"
  - "inst/include/armadillo_bits"

codecov:
 token: 5adfec2d-d501-49a4-a4c7-15fa7d8665b2
