#!/bin/sh

rm -f  config.log config.status confdefs.h \
       src/*.o src/*.so \
       vignettes/RcppArmadillo-unitTests.out \
       vignettes/RcppArmadillo-unitTests.aux \
       vignettes/RcppArmadillo-unitTests.log \
       vignettes/RcppArmadillo-intro.out \
       vignettes/RcppArmadillo*.log \
       vignettes/RcppArmadillo*.aux \
       vignettes/RcppArmadillo*.out \
       vignettes/RcppArmadillo*.tex \
       vignettes/*.blg \
       vignettes/*.bbl \
       vignettes/*~ \
       */*~ *~

rm -rf autom4te.cache/ \
       vignettes/auto/
