# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

armadillo_version <- function(single) {
    .Call('RcppArmadillo_armadillo_version', PACKAGE = 'RcppArmadillo', single)
}

armadillo_set_seed_random <- function() {
    invisible(.Call('RcppArmadillo_armadillo_set_seed_random', PACKAGE = 'RcppArmadillo'))
}

armadillo_set_seed <- function(val) {
    invisible(.Call('RcppArmadillo_armadillo_set_seed', PACKAGE = 'RcppArmadillo', val))
}

fastLm <- function(X, y) {
    .Call('RcppArmadillo_fastLm', PACKAGE = 'RcppArmadillo', X, y)
}

