# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  ci:
    strategy:
      matrix:
        include:
          #- { name: container, os: ubuntu-latest, container: rocker/r2u4ci }
          - { name: macos,     os: macos-latest,  openmp: yes }
          #- { name: macos,     os: macos-latest,  openmp: no }
          - { name: ubuntu,    os: ubuntu-latest }


    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: eddelbuettel/github-actions/r-ci@master

      - name: Configure
        run: ./configure; cat src/Makevars

      - name: Dependencies
        run: ./run.sh install_deps

      - name: Test
        run: ./run.sh run_tests

      - name: Install and Verify on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          R CMD INSTALL .
          Rscript -e 'RcppArmadillo::armadillo_get_number_of_omp_threads()'

      - name: Coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: ./run.sh coverage
