# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  ci:
    strategy:
      matrix:
        include:
          - { name: container, os: ubuntu-latest, container: rocker/r2u4ci }
          - { name: macos,     os: macos-latest,  openmp: yes }
          #- { name: macos,     os: macos-latest,  openmp: no }
          #- { name: ubuntu,    os: ubuntu-latest }


    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: eddelbuettel/github-actions/r-ci@master

      # - name: OpenMP for macOS
      #   if: ${{ matrix.os == 'macos-latest' && matrix.openmp == 'yes' }}
      #   run: |
      #     curl -fsSL https://raw.githubusercontent.com/coatless-shell/openmp/main/install-openmp.sh | bash -s -- --yes
      #     mkdir -p ~/.R
      #     cat <<EOF > ~/.R/Makevars
      #     CPPFLAGS += -Xclang -fopenmp
      #     LDFLAGS += -lomp
      #     EOF
      #     cat ~/.R/Makevars
      #     echo -n "R CMD config CXX: "; R CMD config CXX
      #     echo -n "R CMD config CPPFLAGS: "; R CMD config CPPFLAGS
      #     echo -n "R CMD config LDFLAGS: "; R CMD config LDFLAGS
      #     echo -n "R CMD config SHLIB_CXXLD: "; R CMD config SHLIB_CXXLD
      #     echo -n "R CMD config SHLIB_CXXLDFLAGS: "; R CMD config SHLIB_CXXLDFLAGS

      - name: OpenMP for macOS
        if: ${{ matrix.os == 'macos-latest' && matrix.openmp == 'yes' }}
        run: |
          curl -O https://mac.r-project.org/openmp/openmp-17.0.6-darwin20-Release.tar.gz
          sudo tar fvxz openmp-17.0.6-darwin20-Release.tar.gz -C /
          rm openmp-17.0.6-darwin20-Release.tar.gz
          sudo xcode-select -s /Applications/Xcode_16.2.app
          echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV
          echo "xcode is set: $(xcode-select --print-path)"
          echo "using SDK: $(xcrun --show-sdk-version)"

      - name: Configure
        run: ./configure; cat src/Makevars

      - name: Dependencies
        run: ./run.sh install_deps

      - name: Test
        run: ./run.sh run_tests

      - name: Install and Verify on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          R CMD INSTALL .
          Rscript -e 'RcppArmadillo::armadillo_get_number_of_omp_threads()'

      - name: Coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: ./run.sh coverage
